#!/usr/bin/env bash
# Create the GitHub release for the generated assets.
#
# Usage: scripts/upload_release.sh <tag> [asset ...]
#   e.g. scripts/upload_release.sh v2026.8.0 build/ifs_*.grib2
#
# Prerequisites: gh CLI authenticated; assets already generated by
# scripts/generate_ifs.py; the tag should not exist yet (gh creates it
# from the current commit).
set -euo pipefail

if [ $# -lt 2 ]; then
    echo "usage: $0 <tag> <asset> [asset ...]" >&2
    exit 1
fi
TAG="$1"; shift

gh release create "$TAG" "$@" \
    --title "$TAG" \
    --notes "Frozen ECMWF IFS open-data (CC-BY-4.0) test assets for cedarkit documentation examples.

Asset naming: ifs_<domain>_<run-date><run-time>_f<step>.grib2
- ifs_eastasia_*: parameters 2t/2d/10u/10v/msl/tp, domain 0-60N, 60-150E, 0.25 deg — read/plot examples
- ifs_global_*: parameter 2t, global 0.25 deg — regrid/area operator examples

See README.md and NOTICE for data semantics and attribution."
